CONNECT /as sysdba;

CREATE USER u1 IDENTIFIED BY gkck;

CREATE USER u2 IDENTIFIED BY deep;

GRANT CREATE SESSION TO u1;
GRANT CREATE TABLE TO u1;
GRANT UNLIMITED TABLESPACE TO u1;

CONNECT u1/gkck;

CREATE TABLE emp (
  Eno NUMBER (5) PRIMARY KEY,
  Ename VARCHAR2 (30)
);

INSERT INTO emp VALUES (1,'Employee1');
INSERT INTO emp VALUES (2,'Employee2');
INSERT INTO emp VALUES (3,'Employee3');
INSERT INTO emp VALUES (4,'Employee4');
INSERT INTO emp VALUES (5,'Employee5');

SELECT * FROM emp;

CONNECT /as sysdba;

GRANT CREATE SESSION TO u2;
GRANT CREATE TABLE TO u2;
GRANT UNLIMITED TABLESPACE TO u2;

CONNECT u2/deep;

CREATE DATABASE LINK r
CONNECT to u1
IDENTIFIED BY gkck 
USING 'XE';

SELECT * FROM emp@r;